#!/usr/bin/env bash
set -e

cd

pushd .abode
rm -rf bash-it
git clone git://github.com/Bash-it/bash-it.git
rm -rf dotfiles
git clone git://github.com/JrGoodle/dotfiles.git
popd

.abode/script/bootstrap

rm -rf .abode
git clone --recursive git@github.com:JrGoodle/abode.git .abode
