#!/usr/bin/env bash

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.." || exit 1


git diff --cached --quiet && git pull
git diff --cached --quiet && git submodule update --init --recursive

script/bootstrap

echo 'Update Homebrew formulas'
brew update
brew upgrade
brew cask upgrade
brew cleanup

echo 'Update Mac App Store apps'
mas upgrade

echo 'Update Python packages'
pip3 install --upgrade pip
pip3 install --upgrade -r 'requirements.txt'

echo 'Update Ruby gems'
bundle update
gem cleanup

echo 'Update Node packages'
nvm install node --reinstall-packages-from=node --latest-npm
